services:
  devhabit.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - /Users/kosta/docker-shared/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - /Users/kosta/docker-shared/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /Users/kosta/docker-shared/ASP.NET/Https:/home/app/.aspnet/https:ro
      - /Users/kosta/docker-shared/ASP.NET/Https:/root/.aspnet/https:ro