name: Build

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    DOTNET_VERSION: "9.x"

defaults:
    run:
        working-directory: .

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Show working directory
              run: pwd

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                    dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore
              run: dotnet restore DevHabit.sln

            - name: Build
              run: dotnet build DevHabit.sln --configuration Release --no-restore
    
            - name: Test
              run: dotnet test DevHabit.sln --configuration Release --no-build

            - name: Publish
              run: dotnet publish DevHabit.sln --configuration Release --no-restore --no-build